### PR TITLE
Fix some untranslatable strings

### PR DESCRIPTION
**Pull request by davidwebca**
A client of mine needed the admin strings translated to French so I figured I would send back the work. It's just a bit of cleanup to pass some leftover strings to the twig filter + translatable dates.

Edit: P.S.: If you're interested in getting the French translation too, just let me know. I'd be more than happy to give it back too.

### CODE REVIEW

**Comment by lindseydiloreto** [comment]
Merged, thank you! 🍺 

I'd be happy to add the French translation as well. Would you mind sending it over?

**Comment by lindseydiloreto** [comment]
This has been released in Ad Wizard **v3.2.1**. Feel free to send me the French translations whenever you get a chance!

**Comment by davidwebca** [comment]
> This has been released in Ad Wizard **v3.2.1**. Feel free to send me the French translations whenever you get a chance!

Thanks! Just got back from vacation, I'll sent it to you as soon as possible.

**Comment by lindseydiloreto** [comment]
Excellent, thank you! And welcome back!

**Pull request merged**
